# compose-files list is the source compose file gathered from -c init flag.
compose-files:
  # source can be updated with `kev reload -c other_compose_file`.
#  - source: /absolute/path/examples/wordpress-mysql/docker-compose.yaml
  - source: /Users/ezo/Projects/Go/src/github.com/appvia/kube-devx/examples/wordpress-mysql/docker-compose.yaml
    # cache is internal version of the file to watch and diff against source.
    cache: /Users/ezo/Projects/Go/src/github.com/appvia/kube-devx/.kev.label/.cache/docker-compose.yaml

# environments map for overriding compose config.
# environments are NOT optional, if non are provided then a `local` env is created
environments:
  dev: ./compose.dev.yaml
...
#  staging: ./compose.local.yaml # local env config

#type Definition struct {
#  Name string
#  ComposeFiles []ConfigTuple
#  Overrides map[string]FileConfig
#  LastRender []FileConfig
#}
#
#type ConfigTuple struct {
#  Source FileConfig
#  Cache FileConfig
#}