---
version: 2.1

orbs:
  go: circleci/go@1.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.14'
    steps:
     - checkout
     - go/load-cache
     - go/mod-download
     - go/save-cache
     - go/test:
        covermode: atomic
        failfast: true
        race: true

  e2e:
    machine:
      enabled: true
    steps:
      - checkout
      - run: make setup-kind e2e

workflows:
  main:
    jobs:
      - build

  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e