version: "3.7"
services:
  db:
    x-k8s:
      service:
        type: ClusterIP
      workload:
        imagePull:
          policy: IfNotPresent
        livenessProbe:
          type: exec
          exec:
            command:
              - echo
              - Define healthcheck command for service
          failureThreshold: 3
          successThreshold: 1
          initialDelay: 1m0s
          period: 1m0s
          timeout: 10s
        readinessProbe:
          type: tcp
          tcp:
            port: 3306
        replicas: 1
        resource:
          cpu: 0.1
          maxCpu: 0.5
          maxMemory: 500Mi
          memory: 10Mi
        rollingUpdateMaxSurge: 1
        serviceAccountName: default
        type: StatefulSet
  wordpress:
    x-k8s:
      service:
        type: LoadBalancer
      workload:
        imagePull:
          policy: IfNotPresent
        livenessProbe:
          type: tcp
          tcp:
            port: 8000
          failureThreshold: 3
          successThreshold: 1
          initialDelay: 1m0s
          period: 1m0s
          timeout: 10s
        replicas: 5
        resource:
          cpu: 0.1
          maxCpu: 0.5
          maxMemory: 500Mi
          memory: 10Mi
        rollingUpdateMaxSurge: 1
        serviceAccountName: default
        type: Deployment
volumes:
  db_data:
    x-k8s:
      size: 100Mi
      storageClass: standard
