version: '3.9'
services:
  frontend:
    image: ezodude/frontend-cok8s:prod
    build:
      context: .
      dockerfile: frontend.Dockerfile
    environment:
      PORT: ${PORT}
    ports:
    - '80:8080'
    networks:
     - prod-esnet

  backend:
    image: ezodude/backend-cok8s:prod
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - CACHE_ENDPOINT
      - CACHE_PASSWORD
    networks:
      - prod-esnet

networks:
  prod-esnet:
    driver: bridge